name: CI/CD for React App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' # Adjust the version as needed

      - name: Install dependencies
        run: npm install
      
      - name: check scripts
        run: npm run

      - name: Build
        run: npm run build

